# Copyright 2017 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# All access to services, configmaps, deployments, ingresses and HPAs limited to the "nuclio" namespace
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: chen116-function-deployer
  namespace: chen116
rules:
- apiGroups: [""]
  resources: ["services", "configmaps", "pods", "pods/log"]
  verbs: ["*"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]

---

# Bind the "chen116" service account (used by controller / playground) to the chen116-function-deployer role,
# allowing them to create deployments, services, etc
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: chen116-function-deployer-rolebinding
  namespace: chen116
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chen116-function-deployer
subjects:
- kind: ServiceAccount
  name: chen116
  namespace: chen116

---

# All access to the function/project/functionevents custom resource definition
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: chen116-functioncr-admin
rules:
- apiGroups: ["chen116.io"]
  resources: ["functions", "projects", "functionevents"]
  verbs: ["*"]

---

# Bind the "chen116" service account (used by controller / playground) to the chen116-functioncr-admin role,
# allowing them to create / delete function custom resource definitions in the "chen116" namespace
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: chen116-functioncr-admin-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chen116-functioncr-admin
subjects:
- kind: ServiceAccount
  name: chen116
  namespace: chen116

---
